1.The Slowness of Loops

The relative sluggishness of Python generally manifests itself in situations where
many small operations are being repeated; for instance, looping over arrays to operate
on each element. For example, imagine we have an array of values and we’d like to
compute the reciprocal of each. A straightforward approach might look like this:

In [2]:
import numpy as np
rng = np.random.default_rng(seed=1701)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [3]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.68 s ± 18.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


2. Introducing Ufuncs

In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [5]:
%timeit (1.0 / big_array)

5.06 ms ± 888 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [8]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

3.Exploring NumPy’s Ufuncs

In [10]:
x = np.arange(4)
print("x     = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x // 2 = ", x // 2) # floor division

x     =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [11]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [12]:
-(0.5*x + 1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [13]:
np.add(x, 2)

array([2, 3, 4, 5])

In [16]:
'''
Arithmetic operators implemented in NumPy
Operator           Equivalent       ufunc Description
  +                 np.add           Addition (e.g., 1 + 1 = 2)
  -                 np.subtract      Subtraction (e.g., 3 - 2 = 1)
  -                 np.negative      Unary negation (e.g., -2)
  *                 np.multiply      Multiplication (e.g., 2 * 3 = 6)
  /                 np.divide        Division (e.g., 3 / 2 = 1.5)
  //                np.floor_divide  Floor division (e.g., 3 // 2 = 1)
  **                np.power         Exponentiation (e.g., 2 ** 3 = 8)
  %                 np.mod           Modulus/remainder (e.g., 9 % 4 = 1)
  '''

'\nArithmetic operators implemented in NumPy\nOperator           Equivalent       ufunc Description\n  +                 np.add           Addition (e.g., 1 + 1 = 2)\n  -                 np.subtract      Subtraction (e.g., 3 - 2 = 1)\n  -                 np.negative      Unary negation (e.g., -2)\n  *                 np.multiply      Multiplication (e.g., 2 * 3 = 6)\n  /                 np.divide        Division (e.g., 3 / 2 = 1.5)\n  //                np.floor_divide  Floor division (e.g., 3 // 2 = 1)\n  **                np.power         Exponentiation (e.g., 2 ** 3 = 8)\n  %                 np.mod           Modulus/remainder (e.g., 9 % 4 = 1)\n  '

In [17]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [18]:
# The corresponding NumPy ufunc is np.absolute
np.absolute(x)

array([2, 1, 0, 1, 2])

In [19]:
# which is also available under the alias np.abs:
np.abs(x)

array([2, 1, 0, 1, 2])

In [20]:
# This ufunc can also handle complex data, in which case it returns the magnitude:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [21]:
# Trigonometric functions

In [26]:
theta = np.linspace(0, np.pi, 3) # This creates a NumPy array of 3 evenly spaced values between 0 and π
 # ≈ [0, π/2, π]

In [24]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [27]:
#  Inverse trigonometric functions
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [28]:
# Exponents and Logarithms

In [30]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


In [31]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [32]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


4.Specialized Ufuncs

In [33]:
from scipy import special

In [36]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x)) # The gamma function is a generalization of the factorial
print("ln|gamma(x)| =", special.gammaln(x)) # Computes the natural logarithm of the absolute value of the gamma function
print("beta(x, 2) =", special.beta(x, 2)) # The beta function is a special function that is closely related to the gamma function

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [38]:
# Error function (integral of Gaussian),
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x)) # The error function is used in probability, statistics, and partial differential equations
print("erfc(x) =", special.erfc(x)) # For large 𝑥, erf(x) becomes very close to 1, and computing 1 - erf(x) may lose precision. So erfc(x) gives a numerically stable result.
print("erfinv(x) =", special.erfinv(x)) # The inverse error function is used to find the value of 𝑥 such that erf(𝑥) = 𝑦 for a given 𝑦

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


5.Advanced Ufunc Features

In [ ]:
x = np.arange(5)        # Creates array: [0, 1, 2, 3, 4]
y = np.empty(5)         # Creates an empty array of the same shape (contents uninitialized)
np.multiply(x, 10, out=y)  # Multiplies x * 10 and stores the result in y
print(y)
# The np.multiply function is a universal function (ufunc) that performs element-wise multiplication

[ 0. 10. 20. 30. 40.]


In [41]:
y = np.zeros(10)              # y = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
np.power(2, x, out=y[::2])    # Computes 2^x and stores in every second element of y (indices 0, 2, 4, 6, 8)
print(y)


[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [42]:
# Aggregations

In [44]:
x = np.arange(1, 6) # x = [1, 2, 3, 4, 5]
np.add.reduce(x) # Applies the addition operator cumulatively across the array.(1 + 2 + 3 + 4 + 5)

np.int64(15)

In [ ]:
np.multiply.reduce(x) # np.multiply.reduce(x) applies the multiplication operator cumulatively:
# 1 * 2 * 3 * 4 * 5 = 120

np.int64(120)

In [46]:
np.add.accumulate(x) # np.add.accumulate(x) computes the cumulative sum of the elements in x.
# Instead of a single sum, it returns an array where each element is the sum of all previous elements up to that position.
'''
Calculation:
Index 0: 1
Index 1: 1+2=3
Index 2: 1+2+3=6
Index 3: 1+2+3+4=10
Index 4: 1+2+3+4+5=15
'''



'\nCalculation:\nIndex 0: 1\nIndex 1: 1+2=3\nIndex 2: 1+2+3=6\nIndex 3: 1+2+3+4=10\nIndex 4: 1+2+3+4+5=15\n'

In [48]:
np.multiply.accumulate(x)
'''
Calculates the running product at each index:

Index 0: 1
Index 1: 1×2=2
Index 2: =1×2×3=6
Index 3: 1×2×3×4=24
Index 4: 
1×2×3×4×5=120

'''

'\nCalculates the running product at each index:\n\nIndex 0: 1\nIndex 1: 1×2=2\nIndex 2: =1×2×3=6\nIndex 3: 1×2×3×4=24\nIndex 4: \n1×2×3×4×5=120\n\n'

In [50]:
x = np.arange(1, 6)
np.multiply.outer(x, x) # The outer product of two vectors a and b produces a matrix where each element is the product of an element from a with an element from b.
'''
Calculation:
| × | 1 | 2  | 3  | 4  | 5  |
| - | - | -- | -- | -- | -- |
| 1 | 1 | 2  | 3  | 4  | 5  |
| 2 | 2 | 4  | 6  | 8  | 10 |
| 3 | 3 | 6  | 9  | 12 | 15 |
| 4 | 4 | 8  | 12 | 16 | 20 |
| 5 | 5 | 10 | 15 | 20 | 25 |

'''

'\nCalculation:\n| × | 1 | 2  | 3  | 4  | 5  |\n| - | - | -- | -- | -- | -- |\n| 1 | 1 | 2  | 3  | 4  | 5  |\n| 2 | 2 | 4  | 6  | 8  | 10 |\n| 3 | 3 | 6  | 9  | 12 | 15 |\n| 4 | 4 | 8  | 12 | 16 | 20 |\n| 5 | 5 | 10 | 15 | 20 | 25 |\n\n'