In [3]:
# We can create a list of integers as follows
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [5]:
#  similarly, a list of strings
L2 = [str(c) for c in L]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L2[0])

str

In [7]:
# Because of Python’s dynamic typing, we can even create heterogeneous lists
L3 = [True, "2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

Fixed-Type Arrays in Python

In [10]:
import array
L = list(range(10))
A = array.array('i',L)
A
# here i is the type code indicatating the contents are integers

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating Arrays from Python Lists

In [11]:
import numpy as np

In [13]:
# integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [15]:
#Remember that unlike Python lists, NumPy arrays can only contain data of the same type. If the types do not match, NumPy will upcast them according to its type promo‐tion rules; here, integers are upcast to floating point
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [17]:
# If we want to explicitly set the data type of the resulting array, we can use the dtype
# keyword
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [19]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
# This generates a list of range objects:
# For i = 2, range(2, 5) → [2, 3, 4]
# For i = 4, range(4, 7) → [4, 5, 6]
# For i = 6, range(6, 9) → [6, 7, 8]

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [21]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3,3))

array([[0.0424089 , 0.91459059, 0.92647835],
       [0.48174497, 0.14946251, 0.74794077],
       [0.10552558, 0.50886685, 0.56987746]])

In [30]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
# generates a 3x3 NumPy array of random values drawn from a normal (Gaussian) distribution with:
# mean (loc) = 0
# standard deviation (scale) = 1
# shape = (3, 3)

array([[ 0.1631638 ,  0.40286825, -0.12448154],
       [-0.2521594 , -0.69958179,  0.35020035],
       [ 0.38074337, -1.25731871,  0.52519489]])

In [31]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 7, 4],
       [8, 7, 0],
       [3, 8, 2]], dtype=int32)

In [32]:
# Create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])