We’ll cover a few categories of basic array manipulations here:
Attributes of arrays:
    Determining the size, shape, memory consumption, and data types of arrays
Indexing of arrays:
    Getting and setting the values of individual array elements
Slicing of arrays:
    Getting and setting smaller subarrays within a larger array
Reshaping of arrays:
    Changing the shape of a given array
Joining and splitting of arrays:
    Combining multiple arrays into one, and splitting one array into many

1.NumPy Array Attributes

In [3]:
import numpy as np
rng = np.random.default_rng(seed=1701) # Seed for reproducibility

x1 = rng.integers(10, size = 6) # one dimensional array
x2 = rng.integers(10, size = (3, 4)) # two dimensional array
x3 = rng.integers(10, size = (2, 3, 4)) # three dimensional array


Each array has attributes including ndim (the number of dimensions), shape (the size of each dimension), size (the total size of the array), and dtype (the type of each
element)

In [2]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (2, 3, 4)
x3 size: 24
x3 dtype: int64


2.Array Indexing: Accessing Single Elements

In [4]:
x1

array([9, 4, 0, 3, 8, 6])

In [5]:
x1[0]

np.int64(9)

In [6]:
x1[4]

np.int64(8)

In [7]:
x1[-1]

np.int64(6)

In [8]:
x1[-2]

np.int64(8)

In [9]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [10]:
# In a multidimensional array, items can be accessed using a comma-separated (row, column) tuple:
x2[0, 0]

np.int64(3)

In [11]:
x2[2, 0]

np.int64(0)

In [12]:
x2[2, -1]

np.int64(9)

In [13]:
# Values can also be modified using any of the preceding index notation:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means,
for example, that if you attempt to insert a floating-point value into an integer array,
the value will be silently truncated.

In [14]:
x1[0] = 3.1415
x1

array([3, 4, 0, 3, 8, 6])

3.Array Slicing: Accessing Subarrays(x[start:stop:step])

In [15]:
x1

array([3, 4, 0, 3, 8, 6])

In [16]:
x1[:3] # first three elements

array([3, 4, 0])

In [19]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [20]:
x1[1:4] # middle sub-array

array([4, 0, 3])

In [23]:
x1[::2] # every second element skip one

array([3, 0, 8])

In [24]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

In case the step value is negative the default for start and stop are swapped. This is convenieent to reverse an array

In [26]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [27]:
x1[4::-2] # Every second element, reversed, starting at index 4

array([8, 0, 3])

In [28]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [29]:
x2[:2, :3] # first two rows, first three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [30]:
x2[:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [31]:
x2[::-1, ::-1] # all rows and columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [32]:
x2[:, 0] # first column of x2

array([12,  4,  0])

In [34]:
x2[0, :] # first row of x2

array([12,  1,  3,  7])

In [35]:
x2[0] # equivalent to x2[0, :], first row of x2

array([12,  1,  3,  7])

In [36]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [39]:
x2_sub = x2[:2, :2] # first two rows, first two columns(2*2)
print(x2_sub)

[[12  1]
 [ 4  0]]


In [40]:
x2_sub[0, 0] = 99 # modify the sub-array
print(x2_sub)

[[99  1]
 [ 4  0]]


In [41]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


4.Creating Copies of Arrays

In [42]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


Now, we can modify the subarray, the origial array is not touched

In [44]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [45]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


5.Reshaping of Arrays

In [48]:
# Put the numbers 1 through 9 in a 3 × 3 grid
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


A common reshaping operation is converting a one-dimensional array into a two-
dimensional row or column matrix


In [49]:
x = np.array([1, 2, 3])
x.reshape(1, 3) # row vector 

array([[1, 2, 3]])

In [50]:
x.reshape((3, 1)) # column vector

array([[1],
       [2],
       [3]])

In [51]:
# A convenient shorthand for this is to use np.newaxis in the slicing syntax

In [52]:
x[np.newaxis, :]  # row vector

array([[1, 2, 3]])

In [53]:
x[:, np.newaxis]  # column vector

array([[1],
       [2],
       [3]])

6.Array Concatenation and Splitting

In [54]:
# Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])  # concatenate along the first axis (default)

array([1, 2, 3, 3, 2, 1])

In [58]:
# concatenate more than two arrays at once
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [65]:
# it can be used for two dimensional arrays as well
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [66]:
# Concatenate along the first axis (row-wise)
np.concatenate([grid, grid])  


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
# (vertical stack) and np.hstack (horizontal stack) functions:


In [69]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
# Horizontally stack the arrays
y = np.array([[99],
             [99]])
np.hstack([grid, y])  # horizontal stack

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

7. Splitting of Arrays

In [71]:
# The opposite of concatenation is splitting, which is implemented by the functions
# np.split, np.hsplit, and np.vsplit.

In [72]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # split at indices 3 and 5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper, lower = np.vsplit(grid, [2])  # split into upper and lower halves
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left, right = np.hsplit(grid, [2])  # split into left and right halves
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
